# -- programming courses --
https://www.youtube.com/watch?v=rQoqCP7LX60&list=PLxgZQoSe9cg1drBnejUaDD9GEJBGQ5hMt
https://www.youtube.com/watch?v=OYvlznJ4IZQ&list=PLMCXHnjXnTnt-aA0yHoa6QcVdQ0Mu3g9j
https://www.youtube.com/watch?v=saNiKk06f1Y&list=PLPIwNooIb9vgB1DQEftkKA3qOdeC4vonA
https://www.youtube.com/watch?v=FpvnF7_-tW8&list=PLV8vIYTIdSnYsdt0Dh9KkD9WFEi7nVgbe
https://www.youtube.com/watch?v=kmeaG_BQZ7M&list=PLrjkTql3jnm_yol-ZK1QqPSn5YSg0NF9r
https://www.youtube.com/watch?v=TjZBTDzGeGg&list=PLUl4u3cNGP63gFHB6xb-kVBiQHYe_4hSi
https://www.youtube.com/watch?v=uB3i-qV6VdM&list=PLxCzCOWd7aiHGhOHV-nwb0HR5US5GFKFI
https://www.youtube.com/watch?v=saNiKk06f1Y&list=PLPIwNooIb9vj7cJMxcfcJ6DfSoYL8e8eo&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=3tDE4hDaYgw&list=PLxf3-FrL8GzTIQpnY_UyzDX6JK0_Kbe_t&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=y39OlGrVFD8&list=PLYwpaL_SFmcBmfMtX5wRMAtqna7pY-YtG
https://www.youtube.com/watch?v=AgGu96_rnXo&list=PLYio3GBcDKsPP2_zuxEp8eCulgFjI5a3g
https://www.youtube.com/watch?v=Y4qO9unerGs&list=PLYwpaL_SFmcBhOEPwf5cFwqo5B-cP9G4P
https://www.youtube.com/watch?v=OugnpxNl4_Q&list=PLlpUUtQ9RrF76jvALwrTp0oOGfk0EGC3s
https://www.youtube.com/watch?v=OZkYkWYNTRo&list=PL5vhyNmOQ5ORE-wzDcfhQZiRM7jESvzhD
https://www.youtube.com/watch?v=cNkUna4z6As&list=PLPIwNooIb9vjSzFNtIcivrqJeB0fHcuJH
https://www.youtube.com/watch?v=ZftI2fEz0Fw&list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH
https://www.youtube.com/watch?v=NgWujOrCZFo&list=PLkDaE6sCZn6GMoA0wbpJLi3t34Gd8l0aK
https://www.youtube.com/watch?v=kPlLv6pC3JE&list=PLlHtucAD9KT3mCqOBIrJwO2rsfia_wj1U&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=rtvZFF0xpkU&list=PLoJ8Mlr19CTga-G4MjcpQfVyS4JRzLRNS&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=nqowUJzG-iM&list=PL_z_8CaSLPWekqhdCPmFohncHwz8TY2Go
https://www.youtube.com/watch?v=YYXdXT2l-Gg&list=PL-osiE80TeTskrapNbzXhwoFUiLCjGgY7
https://www.youtube.com/watch?v=EjavYOFoJJ0&list=PLdo5W4Nhv31a8UcMN9-35ghv8qyFWD9_S
https://www.youtube.com/watch?v=l0qvxPPISuY&list=PLVlQHNRLflP8_DGKcMoRw-TYJJALgGu4J
https://www.youtube.com/watch?v=7wnove7K-ZQ&list=PLu0W_9lII9agwh1XjRt242xIpHhPT2llg
https://www.youtube.com/watch?v=17WoOqgXsRM&list=PLRqwX-V7Uu6ZiZxtDDRCi6uhfTH4FilpH
https://www.youtube.com/watch?v=YOVicRQ6QKE&list=PLqleLpAMfxGAdqZeY_4uVQOPCnAjhH-eT
https://www.youtube.com/watch?v=qn0VbSFeTyY&list=PLLOxZwkBK52DmuHRO3UNpqAzDF57FtIxk
https://www.youtube.com/watch?v=8mAITcNt710&list=PLWKjhJtqVAblfum5WiQblKPwIbqYXkDoC
https://www.youtube.com/watch?v=oPjZK4Apgug&list=PLjVLYmrlmjGdmPrz0Lx7smkd0qIKHInOF
https://www.youtube.com/watch?v=SQHREey_Yuc&list=PLfVsf4Bjg79Cu5MYkyJ-u4SyQmMhFeC1C&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=hnj-7XwTYRI&list=PLPW8O6W-1chwyTzI3BHwBLbGQoPFxPAPM&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=Vgu82wiiZ90&list=PLe7Ei6viL6jGp1Rfu0dil1JH1SHk9bgDV
https://www.youtube.com/watch?v=XDuWyYxksXU&list=PLDoPjvoNmBAwy-rS6WKudwVeb_x63EzgS&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=unRhxbFULII&list=PLinedj3B30sA_M0oxCRgFzPzEMX3CSfT5
https://www.youtube.com/watch?v=T_KrYLW4jw8&list=PLzMcBGfZo4-nyLTlSRBvo0zjSnCnqjHYQ
https://www.youtube.com/watch?v=OX9HJsJUDxA&list=PLai5B987bZ9CoVR-QEIN9foz4QCJ0H2Y8
https://www.youtube.com/watch?v=wq56EAYZqGg&list=PLO5VPQH6OWdXR8NlZt0jRbC39W_IyzS-v
https://www.youtube.com/watch?v=lTjGt17bQ3k&list=PLDbRgZ0OOEpUkWDGqp91ODn0dk7LPBAUL
https://www.youtube.com/watch?v=K7hlPhtAZ48&list=PLTgRMOcmRb3M2fbwAgclKI0yt4uVchwZH&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=WpOivQLjhJA&list=PLj_VrUwyDuXS4K3n7X4U4qmkjpuA8rJ76
https://www.youtube.com/watch?v=EYqceb2AnkU&list=PLJbE2Yu2zumDF6BX6_RdPisRVHgzV02NW
https://www.youtube.com/watch?v=cSD3HzkvQoI&list=PL5dTjWUk_cPYuhHm9_QImW7_u4lr5d6zO
https://www.youtube.com/watch?v=zJgwVppKXJ0&list=PLUcsbZa0qzu0gVRFlVfscqjD84TqMssOt
https://www.youtube.com/watch?v=1993zSY5UBI&list=PLA3GkZPtsafacdBLdd3p1DyRd5FGfr3Ue
https://www.youtube.com/watch?v=90hAvj0A8C8&list=PL6W8uoQQ2c60g6_fcjDCLHSx1LBeVYqyZ
https://www.youtube.com/watch?v=Zxwq3aW9ctU&list=PLsyeobzWxl7qbKoSgR5ub6jolI8-ocxCF
https://www.youtube.com/watch?v=bfLAYcPdAMc&list=PL-bgVzzRdaPhNeXyQBtp8hMlUc14J2kRK
https://www.youtube.com/watch?v=q5YSk2Em0TU&list=PLYQLxi4fXFVYKC6xaMag44A8DURXWpsLB
https://www.youtube.com/watch?v=H2gquNz1bvs&list=PL2xsxmVse9IaxzE8Mght4CFltGOqcG6FC
https://www.youtube.com/watch?v=lh1oQHXVSc0&list=PLSVW22jAG8pBnhAdq9S8BpLnZ0_jVBj0c
https://www.youtube.com/watch?v=JoJ8Sw5Yb4c&list=PLRAV69dS1uWQGDQoBYMZWKjzuhCaOnBpa&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=YmGp5Uzh4ag&list=PLXQpH_kZIxTWUe-Ee-DZEX5gfeoo4tHV6
https://www.youtube.com/watch?v=eSrr4YT24Y4&list=PLq3etM-zISamTauFTO5-G5dqBN07ckzTk
https://www.youtube.com/watch?v=75lJDVT1h0s&list=PLzMcBGfZo4-mtY_SE3HuzQJzuj4VlUG0q
https://www.youtube.com/watch?v=ASBUp7stqjo&list=PL5dTjWUk_cPYztKD7WxVFluHvpBNM28N9
https://www.youtube.com/watch?v=EdD8kuiFStY&list=PLTasIXUHepx0tYvXfFsbEl69VbMCZDH1i&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=29_Kg1mwL4g&list=PL7kXAf0BmEquweglCJ9BkSvWXydRDrGfN
https://www.youtube.com/watch?v=qR0WnWL2o1Q&list=PL3eAkoh7fypr8zrkiygiY1e9osoqjoV9w
https://www.youtube.com/watch?v=-ULC_rrdscM&list=PLpCqPSEm2Xe8sEY2haMDUVgwbkIs5NCJI
# -- language courses --
https://www.youtube.com/watch?v=OnSUWIyQqIc&list=PLAX41TUzaphC09B9HFfEqOkwBqCk1yE9v
https://www.youtube.com/watch?v=CbPy_CjJR90&list=PL2IkMHFHWdEqi0jiLXTEakULNDXGc-q_B
https://www.youtube.com/watch?v=1lVqOZ4FKQw&list=PLXmMHVdWuJna5hTAmUgHZZGVTk17l6CFd
https://www.youtube.com/watch?v=qWgjx-Q9iwY&list=PLOCvbe7RB9fZMMtLM5IP-1oBVxjYownyc
https://www.youtube.com/watch?v=erHTtZSk-es&list=PLRo17c5hvJxDVzMp2g_cwthS5kHj0eH0h
https://www.youtube.com/watch?v=O746KEUZlXs&list=PLAX41TUzaphDa3LtzzRZYWS5_MPUF0nz5
https://www.youtube.com/watch?v=IeaadwctbD4&list=PLAie3YzOYRmley8mMYy1s9XuZYVxW1Ot7
https://www.youtube.com/watch?v=voWBtXjLy2Q&list=PLTyvAtj9OYb00pBe-pnqIB18qXchcvLii
https://www.youtube.com/watch?v=GPKgRJJnnGM&list=PLuqAEYkT95ttWYoTu2mJ8GZEtm2DF9JiH
https://www.youtube.com/watch?v=8IogxPUrW7k&list=PL2IkMHFHWdEo-t2mIKmk_HwrJYOTwlT0i
https://www.youtube.com/watch?v=Jzps8q2es7c&list=PLfSUFKdFlttn1MWrG5Q0-a9Cbm9y3uulX
https://www.youtube.com/watch?v=Jzps8q2es7c&list=PLfSUFKdFlttn1MWrG5Q0-a9Cbm9y3uulX
https://www.youtube.com/watch?v=8IogxPUrW7k&list=PL2IkMHFHWdEo-t2mIKmk_HwrJYOTwlT0i
https://www.youtube.com/watch?v=rGrBHiuPlT0&list=PL4071737C12790477
https://www.youtube.com/watch?v=gi2AeYO-g8E&list=PLag_mhJfCJ-18WyYoklCPxIpYbeRgmWLJ
https://www.youtube.com/watch?v=RsrakMT1h2g&list=PLOcym2c7xnBwU12Flkm5RcLIEhvURQ8TB
https://www.youtube.com/watch?v=dwd_Z917XGI&list=PLbMVogVj5nJRmUlVaKDlcYHdecA_WFLVv
https://www.youtube.com/watch?v=wDpsF90DoeI&list=PLag_mhJfCJ-1-EZcPapMFPTlzVzwjz33M
https://www.youtube.com/watch?v=V3ioRPuBcfw&list=PLwGjqS2iLnwV1lBfUo6VuWmMaWUJnxLMK
https://www.youtube.com/watch?v=PMfPDItcY6M&list=PLWbbTej6f09ihlJqP5_VhKB-WuYUalZrb
https://www.youtube.com/watch?v=pSvH9vH60Ig&list=PLg9uYxuZf8x_A-vcqqyOFZu06WlhnypWj
https://www.youtube.com/watch?v=GUymRdqBglo&list=PLd5-Wp_4tLqZor0fbsXtP7t6npWeE-2IU
https://www.youtube.com/watch?v=0-EG_73y-4k&list=PLZg8mrsd6BzsUZ_YXkcihJEFJLn9Fw29Y
https://www.youtube.com/watch?v=YEAje1C6tBU&list=PL41R2vH_CL40PRnrrD1CMTGVXLiSNQbdo&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=PTb7xjtsOu4&list=PLnrexUoZVMfytYIt7exturRLhjjBOIvfS
https://www.youtube.com/watch?v=2yB-D2oGU40&list=PLi03R8dvV3GyU6Ts_b3C99W5LCojuJ7xL
https://www.youtube.com/watch?v=GaQBL4XHuSo&list=PLA_RcUI8km1NMhiEebcbqdlcHv_2ngbO2
https://www.youtube.com/watch?v=VaUfsPxDUcA&list=PLPSfPyOOcp3Tes7RGG42W_zbLESN7y32i
https://www.youtube.com/watch?v=wSZD7H_5eLQ&list=PLKvm_z0JG6IODoSpnJ2qNCN3UpQi230ns
https://www.youtube.com/watch?v=JMStfbZDt1k&list=PLVWfp7qXLmKVfSUkucXErLncKn-JqgBbK
https://www.youtube.com/watch?v=McZW0iDsZns&list=PLWXyZU_NJb_chvMZ13hgOPB3Vcz7xhW3q
https://www.youtube.com/watch?v=LrNkgDVrKEw&list=PLrYgra2FrMh_jGBcMmNWPnSh-kHwGiaXG
https://www.youtube.com/watch?v=URfKUa1ic3E&list=PLkc2Cu2674rblXRJZuPyjYxgipv47tuD8&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=K94mY0cUH_U&list=PLlHLXsD5BfOvz6UJxxUPhydnNKaX0VZfd
https://www.youtube.com/watch?v=gmkxd91MGjo&list=PLA36tOH9KdEFcUtGAan_sd4yXmq5L7LNu
https://www.youtube.com/watch?v=p9GuL7nXjxQ&list=PLRZWB7bMG3rEotMVIlDys3-GX86xiJuOu
https://www.youtube.com/watch?v=9S67UR832_Q&list=PLOZiEc7ESUiE3Jdo1hkWfNvQpxaamHA9L&pp=0gcJCbAEOCosWNin
https://www.youtube.com/watch?v=6bS4GM09mco&list=PLVWfp7qXLmKXE5TzCtNGXkbqIgAdsrFZw
https://www.youtube.com/watch?v=mfBwNIjMbss&list=PL7VdqFXO0Lzdu2U1q-_vZxcuWyqJEitZV
https://www.youtube.com/watch?v=IoKPvNnH6ug&list=PLeDNB42ERslWp4DpPc7-T_E4UU1bBpPwF
https://www.youtube.com/watch?v=l-KbjVOMzAc&list=PLVWfp7qXLmKUKr2uHPrd2aqimN5UjCGWN
https://www.youtube.com/watch?v=9XbQJPF817I&list=PLWXyZU_NJb_fGUFuJpqjn4vYLzpTZqhC0
https://www.youtube.com/watch?v=wOZji5OKDAY&list=PLneZiE_zP2-whvzCQnPVMGYpRHeI3Bi_H
