spring.application.name=courses
server.port=8082
# Ensure CORS headers deduplicate at gateway; keep service lean

#spring.application.name=onlineCourses
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/course_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
<<<<<<< HEAD
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:matkhaumysql}
=======
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
>>>>>>> c7dbd896d4c291163afeef123ccfb49f9a223906

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huongtran4002@gmail.com
spring.mail.password=mxku efiw hzrf pewg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.security=DEBUG


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/