#spring.application.name=servicethongke
#spring.application.name=btlhdv
server:
  port: 8084
  servlet:
#    context-path: /btl_hdv

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Servicethongke}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:matkhaumysql}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # For Hibernate 6+ use MySQLDialect (MySQL8Dialect class removed)
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      order_inserts: true
      order_updates: true
      format_sql: true
    show-sql: true