spring.application.name=api-gateway

# Gateway server port
server.port=9090

# Route to courses-service
spring.cloud.gateway.routes[0].id=courses-service
spring.cloud.gateway.routes[0].uri=http://localhost:8082
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/courses/**

# Route to lesson-service
spring.cloud.gateway.routes[1].id=lesson-service
spring.cloud.gateway.routes[1].uri=http://localhost:8083
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/lessons/**

# Route to user-service
spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=http://localhost:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/users/**

# Deduplicate CORS headers to avoid comma-separated duplicates
spring.cloud.gateway.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Headers Access-Control-Allow-Methods Access-Control-Max-Age, RETAIN_UNIQUE

