spring.application.name=api-gateway

# Gateway server port
server.port=9090

# Route to lesson-service
spring.cloud.gateway.routes[0].id=lesson-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/lessons/**

# Route to user-service
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/**

